version: '3.3'

networks:
  traefik:
    external:
      name: traefik
  inside:
    external: false

services:
  traefik:
    image: traefik
    env_file:
      - .env
    networks:
      - inside
      - traefik 
    container_name: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${FRONTEND_HTTP_PORT}:80"
      - "${FRONTEND_HTTPS_PORT}:443"
      - "${WEB_UI_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
#      - $PWD/traefik.log:/traefik.log
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:${FRONTEND_DOMAIN}
      - traefik.enable=true
    restart: always
